### ISSUE TITLE
debian11安装网卡ip掉了，安装失败

### ISSUE THREAD

**Issue by zrlhk** [oneclickvirt/incus#1]
第二次重启继续安装到：
Saving to: ‘/etc/systemd/system/check-dns.service’

/etc/systemd/system/check-dns.service           [ <=>                                                                                        ]     145  --.-KB/s    in 0s

2024-03-11 23:53:38 (1.86 MB/s) - ‘/etc/systemd/system/check-dns.service’ saved [145]

Created symlink /etc/systemd/system/multi-user.target.wants/check-dns.service → /etc/systemd/system/check-dns.service.

就卡死了，ip a:
![image](https://github.com/oneclickvirt/incus/assets/9092768/e2f8d40b-2a6d-4ebb-a049-ac6484058d56)

**Comment by spiritLHLS** [comment]
重启网络炸鸡了大概，你后台强制重启服务器看看网络有没有回来？

**Comment by zrlhk** [comment]
的确重启后Ip就回来了
然后也可以按照ui，导入证书使用，好像正常

**Comment by spiritLHLS** [comment]
> 的确重启后Ip就回来了 然后也可以按照ui，导入证书使用，好像正常

大概是装完iptables相关的玩意和一些配置冲突了，遇到这种情况强制重启服务器一般就没问题了，稍后我更新一下说明文档
