### ISSUE TITLE
add_more.sh端口问题

### ISSUE THREAD

**Issue by QASDJKL5** [oneclickvirt/incus#3]
也不少啥大问题，小鸡的端口增加应该改成24，现在是25，会导致开出的小鸡端口非常不整齐

**Comment by spiritLHLS** [comment]
周六日有空我修复一下

**Comment by spiritLHLS** [comment]
https://github.com/oneclickvirt/incus/commit/7ef617e624d9a92a1a887a8f9edfa88624e0e5cd
