### ISSUE TITLE
incus开启的lxc小鸡硬盘显示错误

### ISSUE THREAD

**Issue by EzXxY** [oneclickvirt/incus#4]
我使用incus一键自定义配置批量开lxc小鸡脚本之后，主机上可以显示出【/dev/loop1】一直到【/dev/loop8】

![image](https://github.com/oneclickvirt/incus/assets/63538520/a02a1aec-2660-40b6-b8f5-bb35eb8ddcf3)

但是进入小鸡之后，使用【df -h】命令查看到的挂载盘符却是【/dev/loop0】，且磁盘大小显示总体分配的硬盘空间

![image](https://github.com/oneclickvirt/incus/assets/63538520/a4e957ee-7619-4f7d-b72c-a15a7a5647b8)

请问这是什么原因呢？

**Comment by spiritLHLS** [comment]
实际使用是有限制到了吧？ 如果是btrfs类型的话

**Comment by EzXxY** [comment]
实际使用貌似是有限制，但是我也不太清楚到底有没有限制到全部用户。
分出来的硬盘文件类型确实是btrfs，请问如何让小鸡里的```df -h```命令显示实际的btrfs文件类型硬盘大小呀？
![image](https://github.com/oneclickvirt/incus/assets/63538520/659ec795-5cfe-4e19-a6ce-51402b9bb9c1)

**Comment by spiritLHLS** [comment]
没测试过，安装incus的时候默认初始化时设置了默认的存储池大小，如果不设置默认存储池也许就正常了

**Comment by spiritLHLS** [comment]
你看一下 incus info 容器名字 如果挂载没问题将就用着呗，显示错误不影响使用吧

**Comment by EzXxY** [comment]
是的，目前显示错误但是不影响使用，谢谢啦

> 你看一下 incus info 容器名字 如果挂载没问题将就用着呗，显示错误不影响使用吧
