### ISSUE TITLE
安装incus主体报错

### ISSUE THREAD

**Issue by joyoner** [oneclickvirt/incus#5]
宿主机需要开设多大的存储池？(存储池就是小鸡硬盘之和的大小，推荐SWAP和存储池加起来达到母鸡硬盘的95%空间，注意是GB为单位，需要10G存储池则输入10)：4
Error: Storage has already been configured
trying to use another storage type ......
尝试使用其他存储类型......
Infinite storage pool size using default dir type due to no btrfs
由于无btrfs，使用默认dir类型无限定存储池大小
Error: Storage has already been configured
Use dir storage type failed.
使用 dir 存储类型失败。

**Comment by spiritLHLS** [comment]
```
Error: Storage has already been configured
```

已经初始化默认存储池成功，后续的见 https://github.com/oneclickvirt/incus/issues/4 说明
