### ISSUE TITLE
甲骨文服务器开incus虚拟机，宿主机已经有ipv6了，想给incus虚拟机分配独立的ipv6应该怎么做呢？

### ISSUE THREAD

**Issue by lyd123qw2008** [oneclickvirt/incus#6]
如题，使用一键脚本给incus虚拟机开设出来的同网段的ipv6是不通的，新手小白，请问应该怎么操作？
已阅读说明文档：[转移不同服务器之间的ipv6子网](https://virt.spiritlhl.net/guide/incus/incus_custom.html#%E8%BD%AC%E7%A7%BB%E4%B8%8D%E5%90%8C%E6%9C%8D%E5%8A%A1%E5%99%A8%E4%B9%8B%E9%97%B4%E7%9A%84ipv6%E5%AD%90%E7%BD%91)，觉得还是有些复杂，请问怎么做比较简单？

**Comment by spiritLHLS** [comment]
你确信甲骨文给你附加的IP是/64段吗？
纯净环境使用 

```
curl -L https://raw.githubusercontent.com/spiritLHLS/ecs/main/archive/eo6s.sh -o eo6s.sh && chmod +x eo6s.sh && bash eo6s.sh
```

查看是否确实有

**Comment by lyd123qw2008** [comment]
![image](https://github.com/user-attachments/assets/c19b4638-35e0-4b26-bc3b-8c0510afe972)
您看看
另外补充两张图片：
<img width="1232" alt="78d6197d4adf11563e285ba04277c2e" src="https://github.com/user-attachments/assets/b0cc3875-50ef-4350-a7f0-1670010df00b">
这是给宿主机分配的两个ipv6地址。其中 8a19 的我想分配的虚拟机，e9fe 的我想给宿主机。
<img width="1231" alt="1430188926d56e184ae3ad69acc57f4" src="https://github.com/user-attachments/assets/139870cb-dce8-4055-ad1c-52e71b80ec34">
这是甲骨文申请到的/64段的ipv6前缀

**Comment by spiritLHLS** [comment]
![352807452-c19b4638-35e0-4b26-bc3b-8c0510afe972](https://github.com/user-attachments/assets/87878ce4-6013-4a1d-9f27-8c3f03b6913f)

很怪，看检测的没法正常附加上，显示的是128不是64

**Comment by lyd123qw2008** [comment]
> ![352807452-c19b4638-35e0-4b26-bc3b-8c0510afe972](https://private-user-images.githubusercontent.com/103393591/352808085-87878ce4-6013-4a1d-9f27-8c3f03b6913f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjYwNTAsIm5iZiI6MTcyMjE2NTc1MCwicGF0aCI6Ii8xMDMzOTM1OTEvMzUyODA4MDg1LTg3ODc4Y2U0LTYwMTMtNGExZC05ZjI3LThjM2YwM2I2OTEzZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyOFQxMTIyMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zM2E1Y2VhODY4OGM5OWVkOGEyNTI5NTgyZWZhM2VhMDlmMDI0ZTVhY2EzMjViMDMwNzhjZTc3NDY4MDg2MTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iYkpAFUQ3FjFe22nyiEafc8gPKH4_XvTLREF1TL6Svk)
> 
> 很怪，看检测的没法正常附加上，显示的是128不是64

![image](https://github.com/user-attachments/assets/80ce8ff7-85fe-4e12-9373-7a2d5dd0b64f)

是要64才能自动加上吗？

**Comment by lyd123qw2008** [comment]
![image](https://github.com/user-attachments/assets/5f4352db-9b9e-45cd-aca6-a10b57b65f9d)
我看宿主机的网卡配置只有这些

**Comment by spiritLHLS** [comment]
> ![image](https://private-user-images.githubusercontent.com/28444822/352808352-80ce8ff7-85fe-4e12-9373-7a2d5dd0b64f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjYxMDcsIm5iZiI6MTcyMjE2NTgwNywicGF0aCI6Ii8yODQ0NDgyMi8zNTI4MDgzNTItODBjZThmZjctODVmZS00ZTEyLTkzNzMtN2EyZDVkZDBiNjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDExMjMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NDUyY2VhMzk2MDVlOTc3NjVhZDgxMGNlNTM3ZTlmMTJkOWYzYzY1OWI4YzNlOTUzZGVhM2EyNDY5YzBjN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Cm4NMHZMyN2CVseiAgFXlybDrehxJE__kt6uLgR_Mhc)
> 
> 是要64才能自动加上吗？

你新的图这显示的 prefixlen 128 啊

**Comment by lyd123qw2008** [comment]
> 你新的图这显示的 prefixlen 128 啊

自动的就是 128

**Comment by spiritLHLS** [comment]
![1722166124422](https://github.com/user-attachments/assets/53ba667d-b66a-4621-ae76-18a076e9d129)
我这种就能分

**Comment by spiritLHLS** [comment]
你这种情况大概率类似SLAAC分配的，直接附加哪怕成功了，重启服务器后MAC地址一变，V6也不通

**Comment by lyd123qw2008** [comment]
意思是甲骨文给我分配的是128的ipv6，无法扩展吗？

**Comment by spiritLHLS** [comment]
> 意思是甲骨文给我分配的是128的ipv6，无法扩展吗？

是的

**Comment by spiritLHLS** [comment]
![](https://private-user-images.githubusercontent.com/28444822/352807702-b0cc3875-50ef-4350-a7f0-1670010df00b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjU2NzYsIm5iZiI6MTcyMjE2NTM3NiwicGF0aCI6Ii8yODQ0NDgyMi8zNTI4MDc3MDItYjBjYzM4NzUtNTBlZi00MzUwLWE3ZjAtMTY3MDAxMGRmMDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDExMTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1Yzg3NWVkNWI1NjdmYmQ0OWZjMzdkNTM1MWVhNWM2ODA4ODgzZTU1NTA5ZDI2ZDE1Mzk1NTQxNmNlYmZkMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.njArHwrWVWJde9ge40FvN1Kq3czu0HtNVJUvf-EqLFc)

你这个得改成加/64的

**Comment by lyd123qw2008** [comment]
我买过别人用甲骨文开出来nat机，他也是用incus开出来，然后出售的，我看他附加的ipv6也是甲骨文的ip，所以我也想这么弄一下

**Comment by spiritLHLS** [comment]
> ![](https://private-user-images.githubusercontent.com/28444822/352807702-b0cc3875-50ef-4350-a7f0-1670010df00b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjU2NzYsIm5iZiI6MTcyMjE2NTM3NiwicGF0aCI6Ii8yODQ0NDgyMi8zNTI4MDc3MDItYjBjYzM4NzUtNTBlZi00MzUwLWE3ZjAtMTY3MDAxMGRmMDBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDExMTYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1Yzg3NWVkNWI1NjdmYmQ0OWZjMzdkNTM1MWVhNWM2ODA4ODgzZTU1NTA5ZDI2ZDE1Mzk1NTQxNmNlYmZkMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.njArHwrWVWJde9ge40FvN1Kq3czu0HtNVJUvf-EqLFc)
> 
> 你这个得改成加/64的

来到实例详情中的 附加的VNIC-创建VNIC，选择默认虚拟云网络和子网地址创建
等添加好了后进入这个VNIC-IPV6地址-分配IPV6地址

![5cd0fdf6f291c70be64a22743048603f](https://github.com/user-attachments/assets/a1d85608-30c9-4be9-8472-900970871345)

类似这样

**Comment by lyd123qw2008** [comment]
好，悟了。我试试

**Comment by lyd123qw2008** [comment]
![image](https://github.com/user-attachments/assets/8d6f9c24-026e-455c-b037-53fc4dc6f9f2)
奇怪还是128
![image](https://github.com/user-attachments/assets/25b60cdd-a8af-40d3-898c-050f9b397c5d)

**Comment by spiritLHLS** [comment]
重启了服务器了吗

**Comment by lyd123qw2008** [comment]
> 重启了服务器了吗

重启了

**Comment by spiritLHLS** [comment]
> ![image](https://private-user-images.githubusercontent.com/28444822/352809679-8d6f9c24-026e-455c-b037-53fc4dc6f9f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjc3ODksIm5iZiI6MTcyMjE2NzQ4OSwicGF0aCI6Ii8yODQ0NDgyMi8zNTI4MDk2NzktOGQ2ZjljMjQtMDI2ZS00NTVjLWIwMzctNTNmYzRkYzZmOWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDExNTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NTk3MzMxMDMxYThjYjk1ZjViNzFhYTJmZjk4ODY2NGRiMjVlZDNjNWYyN2RkN2ExMmEyYmIzMTExNDY0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LjnoGKyPMrXU9rWm1FhFmJtwf25zMaHMmJdidhRTlx0) 奇怪还是128 ![image](https://private-user-images.githubusercontent.com/28444822/352809733-25b60cdd-a8af-40d3-898c-050f9b397c5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNjc3ODksIm5iZiI6MTcyMjE2NzQ4OSwicGF0aCI6Ii8yODQ0NDgyMi8zNTI4MDk3MzMtMjViNjBjZGQtYThhZi00MGQzLTg5OGMtMDUwZjliMzk3YzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDExNTEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYjlkMzNkN2UyYTk5ZDNjMDRkZTMxMjIzMWUxMzZjYTdhMzI1NTI0YjJhOGI5YmE5ZmE0NmQxNTAyODQwODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J_p_-5vgT88VJmk8G2bfRujwB1l-JdOyb1cyQXa_cfE)

选右边的手动附加看看，附加64的

**Comment by lyd123qw2008** [comment]
我试试

**Comment by lyd123qw2008** [comment]
![image](https://github.com/user-attachments/assets/36a5f8ba-783b-4386-b6bc-0403bcf2dee8)
这是手动的，设置后重启也一样
![image](https://github.com/user-attachments/assets/85288791-d9a3-459e-9c17-e5e886d58ef2)

**Comment by spiritLHLS** [comment]
怪，宿主机设置有问题，导致的没有子网IP可用，那我也不知道怎么办了

**Comment by lyd123qw2008** [comment]
好吧，我搜索一下资料，谢谢

**Comment by spiritLHLS** [comment]
最后一招，设置后重置系统，也许可能有用也许可能没用，我也搞不来别的了，甲骨文这设置我没弄过

正常的子网你用那个脚本可以查看能不能设置，自己摸索吧

**Comment by lyd123qw2008** [comment]
嗯嗯，好的

**Comment by spiritLHLS** [comment]
哦还有一种极端情况，直接NAT全端口映射，你给宿主机绑定一堆IPV6/128的地址，直接一个个全端口映射incus的内网IPV6地址，这种方法也行

**Comment by spiritLHLS** [comment]
属于是没办法的办法了这种，类似 https://www.spiritlhl.net/guide/pve/pve_kvm.html#%E5%AE%BF%E4%B8%BB%E6%9C%BA%E6%89%8B%E5%8A%A8%E9%99%84%E5%8A%A0%E9%A2%9D%E5%A4%96ipv4%E5%9C%B0%E5%9D%80%E5%90%8E%E5%86%8D%E6%8C%87%E5%AE%9Aipv4%E5%9C%B0%E5%9D%80%E5%BC%80%E8%AE%BE%E8%99%9A%E6%8B%9F%E6%9C%BA

**Comment by spiritLHLS** [comment]
相关文章 https://www.spiritysdx.top/20240111/

**Comment by lyd123qw2008** [comment]
好嘞，谢谢，我看看

**Comment by lyd123qw2008** [comment]
确实这个和nat商家给我附加的ipv6行为比较相似。学习了。

**Comment by spiritLHLS** [comment]
流量会经过转发，有一个出问题别的一起出问题，不如分配的安全，你要自动的你用 https://github.com/oneclickvirt/lxd 就行，有对应脚本用方法1做这种转发的，缺点就是所有系统镜像均为非自编译镜像，开容器开的贼慢，一个个都要初始化

**Comment by lyd123qw2008** [comment]
嗯嗯，好的。不能搞独立ipv6，没什么兴致了。
